### ISSUE TITLE
Support for Volta / Turing architectures

### ISSUE THREAD

**Issue by tgaddair** [flashinfer-ai/flashinfer#160]
I saw that support for sm75 / sm70 is listed in progress (https://docs.flashinfer.ai/installation.html) but didn't see an issue to track. Is this something planned in the near-term or further out on the roadmap? Thanks!

**Comment by aliencaocao** [comment]
its tracked here https://github.com/flashinfer-ai/flashinfer/issues/19 but so far no movements in codebase i think

**Comment by yzh119** [comment]
@aliencaocao @tgaddair part of the work has been done in #128 , still some work to do to accommodate the small shared memory size of sm75.

Regarding sm70, I have made some local attempts but the performance is not good because I'm using a software simulation of `ldmatrix` instrinsic. My plan is to write standalone prefill/decode kernels for sm70 because it supports neither async memory copy nor native ldmatrix intrinsic.

They are still on my TODO list, I suppose I can finish sm75 support soon but it will take some effort to debug and performance tuning on sm70, will try my best..

**Comment by aliencaocao** [comment]
Thanks for the update, looking forward to sm70.

**Comment by K-Mistele** [comment]
This would be really really great since I would love to be able to use this on my volta devices

**Comment by balcklive** [comment]
> @aliencaocao @tgaddair part of the work has been done in #128 , still some work to do to accommodate the small shared memory size of sm75.
> 
> Regarding sm70, I have made some local attempts but the performance is not good because I'm using a software simulation of `ldmatrix` instrinsic. My plan is to write standalone prefill/decode kernels for sm70 because it supports neither async memory copy nor native ldmatrix intrinsic.
> 
> They are still on my TODO list, I suppose I can finish sm75 support soon but it will take some effort to debug and performance tuning on sm70, will try my best..

Can you push the local attemps for sm70?  I'm curious to see, and maybe someone can help to finish it.

**Comment by sparsh35** [comment]
This would be great.

**Comment by zhyncs** [comment]
Turing has been supported with https://github.com/flashinfer-ai/flashinfer/pull/449. Volta currently has no supported plans. Welcome to contribute!

**Comment by valentijnvenus** [comment]
@zhyncs 

> Regarding sm70, I have made some local attempts but the performance is not good because I'm using a software simulation of ldmatrix instrinsic. My plan is to write standalone prefill/decode kernels for sm70 because it supports neither async memory copy nor native ldmatrix intrinsic.

happy to help, may you push your local attemps for sm70 to a new branch pls?
