### ISSUE TITLE
Some questions about kFillZero

### ISSUE THREAD

**Issue by carryyu** [flashinfer-ai/flashinfer#358]
Thanks for your great work!

I have some doubts about kFillZero on V, because the result of q@k has been masked, why do we need to kFillZero on V?

**Comment by carryyu** [comment]
I found there is a probability of precision error after setting it to kNoFill. It seems that this is caused by V being initialized to nan.

**Comment by yzh119** [comment]
Yes we don't need to use kFillZero for K because we have a explicit masking stage, which sets the attention score corresponding of OOB(out-of-boundary) positions to zeros, not matter what their K is.

But we need to use kFillZero for V, but even though the attention score of OOB positions are zeros, the OOB positions of V tile might be inf without explicit filling zero, and the multiply of 0 and inf is nan, which lead to wrong results.

**Comment by carryyu** [comment]
> Yes we don't need to use kFillZero for K because we have a explicit masking stage, which sets the attention score corresponding of OOB(out-of-boundary) positions to zeros, not matter what their K is.
> 
> But we need to use kFillZero for V, but even though the attention score of OOB positions are zeros, the OOB positions of V tile might be inf without explicit filling zero, and the multiply of 0 and inf is nan, which lead to wrong results.

Thanks for your replay!
