### ISSUE TITLE
Where can I find end-to-end examples?

### ISSUE THREAD

**Issue by WoosukKwon** [flashinfer-ai/flashinfer#51]
Hello Team,

Thanks for the great work! It seems FlashInfer has very useful and well-written CUDA kernels for LLM inference. I'm excited to find this repository!

Could you provide some end-to-end examples (or any documentation) of how to use these kernels? I really want to try them out on my machine.

Additionally, I've noticed that some of the kernels appear to reimplement existing algorithms like FlashAttention and PagedAttention. Is there any performance benchmark available that compares these to their original implementations? I'm curious about how the kernels perform.

Thanks!

**Comment by yzh119** [comment]
Hi @WoosukKwon , thanks for your attention.
> Could you provide some end-to-end examples (or any documentation) of how to use these kernels? I really want to try 
them out on my machine.

Sorry I haven't taken time to do that because of limited bandwidth, documentation is one of the priorities for our official release, I'll add some documentation and provide trying-out examples in README.

> Additionally, I've noticed that some of the kernels appear to reimplement existing algorithms like FlashAttention and PagedAttention. Is there any performance benchmark available that compares these to their original implementations? I'm curious about how the kernels perform.

We do have a lot of benchmark results and I'm wrapping up a blog post to describe them. The brief answer is that we are better or on par with existing implementations and I'll explain the performance breakdown analysis in the blog post (Actually, the whole field is evolving so fast and every open-source project keeps improving performance, so it's very important to know how does the performance gain coming from rather than just showing the numbers, and I hope my blog posts would be helpful).

I'm glad that you are interested in this project and I hope we can figure out a set of standard APIs that could benefit a lot of projects. Looking forward to collaborating with you on that if you are interested.

**Comment by WoosukKwon** [comment]
@yzh119 Thanks for the reply. Sounds amazing. Looking forward to the blog post!

**Comment by WoosukKwon** [comment]
Closed as FlashInfer has a nice documentation with examples.
