### ISSUE TITLE
[Question] Support for torch 2.5

### ISSUE THREAD

**Issue by Galaxy-Husky** [flashinfer-ai/flashinfer#689]
Hi, 
I've installed `torch 2.5.1` and want to install `sglang` and `flashinfer`. 

#575 said that torch 2.4 wheels should work for torch 2.5. But it will remove the installed torch and install `torch 2.4.0` when I try running `pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer/`.

What should I do to avoid changing the version of `torch`?

**Comment by zhyncs** [comment]
Torch 2.4 and Torch 2.5 are ABI compatible, so the FlashInfer wheel for Torch 2.4 or Torch 2.5 can be used directly.

**Comment by zhyncs** [comment]
During the installation of SGLang, the version of Torch is determined by the dependent vllm version. v0.6.3.post1 uses Torch 2.4, and v0.6.4.post1 uses Torch 2.5.

**Comment by mbadams5** [comment]
I am hitting the same issue and it is due to this line:
https://github.com/flashinfer-ai/flashinfer/blob/bcf7a3ee0d919eca45d2f07241479b5776975bc3/setup.py#L138

Which is getting set for CI builds here:
https://github.com/flashinfer-ai/flashinfer/blob/bcf7a3ee0d919eca45d2f07241479b5776975bc3/scripts/run-ci-build-wheel.sh#L55

I can get around the issue by building the wheel myself, but this seems like a regression, or at least breaking change, from 0.1.6 and earlier.

**Comment by Galaxy-Husky** [comment]
> During the installation of SGLang, the version of Torch is determined by the dependent vllm version. v0.6.3.post1 uses Torch 2.4, and v0.6.4.post1 uses Torch 2.5.

Yes. I tried again and it worked.
